Initial Version

diff --git a/measure/run_measureadj.sh.template b/measure/run_measureadj.sh.template
--- a/measure/run_measureadj.sh.template
+++ b/measure/run_measureadj.sh.template
@@ -3,8 +3,13 @@
 #SBATCH --account=:account:
 #SBATCH --exclusive
 #SBATCH --export=ALL
-#SBATCH --nodes=1
-#SBATCH --time=01:00:00
+#SBATCH --nodes=:nodes:
+#SBATCH --ntasks=:nproc:
+#SBATCH --time=:time:
+#SBATCH --partition=:partition:
+#SBATCH --array=:array:
+#SBATCH --gres=:gres:
+#SBATCH --output=output_:job_id:.o
 
 STARTTIME=$(date +%s)
 echo "start time is : $(date +"%T")"
@@ -22,6 +27,9 @@ do
 			-p ../adjoint/parfile/multitaper.adjoint.$p.config.yml \
 			-f ./paths/measure.$e.$p.path.json \
 			-v
+		
+		# checks exit code
+		if [ $? -ne 0 ]; then exit 1; fi
     done
 done
 
diff --git a/proc/run_preprocessing.sh.template b/proc/run_preprocessing.sh.template
--- a/proc/run_preprocessing.sh.template
+++ b/proc/run_preprocessing.sh.template
@@ -3,8 +3,13 @@
 #SBATCH --account=:account:
 #SBATCH --exclusive
 #SBATCH --export=ALL
-#SBATCH --nodes=1
-#SBATCH --time=01:00:00
+#SBATCH --nodes=:nodes:
+#SBATCH --ntasks=:nproc:
+#SBATCH --time=:time:
+#SBATCH --partition=:partition:
+#SBATCH --array=:array:
+#SBATCH --gres=:gres:
+#SBATCH --output=output_:job_id:.o
 
 STARTTIME=$(date +%s)
 echo "start time is : $(date +"%T")"
@@ -20,18 +25,23 @@ do
     do
 		echo "++++++"
 		echo "process observed file..."
-		mpirun -np :nproc: pypaw-process_asdf \
-    		-p ./parfile/proc_obsd.${p}.param.yml \
-    		-f ./paths/proc_obsd.${e}.${p}.path.json \
-    		-v
+		mpirun -np :nproc: python proc.py \
+    		./parfile/proc_obsd.${p}.param.yml \
+    		./paths/proc_obsd.${e}.${p}.path.json
+
+		# checks exit code
+		if [ $? -ne 0 ]; then exit 1; fi
+		
+    	       
 
 		echo "++++++"
 		echo "process synthetic file..."
-		mpirun -np :nproc: pypaw-process_asdf \
-    		-p ./parfile/proc_synt.${p}.param.yml \
-    		-f ./paths/proc_synt.${e}.${p}.path.json \
-    		-v
-		echo "++++++"
+		mpirun -np :nproc: python proc.py \
+    		       ./parfile/proc_synt.${p}.param.yml \
+    		       ./paths/proc_synt.${e}.${p}.path.json 
+		       
+		# checks exit code
+		if [ $? -ne 0 ]; then exit 1; fi
     done
 done
 
